project_id = "pooebqhsshfafkhvccrl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[edge_runtime]
enabled = true

[functions.ai-interpret-calculator]
verify_jwt = false

[functions.blog-ai-optimizer]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.sitemap-xml]
verify_jwt = false

[functions.robots-txt]
verify_jwt = false

[functions.sitemap-index]
verify_jwt = false

[functions.sleep-ai-analysis]
verify_jwt = false

[functions.generate-blog-sitemap]
verify_jwt = false

[functions.blog-rss]
verify_jwt = false

[functions.ping-google-sitemap]
verify_jwt = false

[functions.google-sitemap-ping]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false

[functions.claude-chat]
verify_jwt = false

[functions.website-crawler]
verify_jwt = true

[functions.generate-main-sitemap]
verify_jwt = false

[functions.generate-sitemap-index]
verify_jwt = false

[functions.generate-sitemap-locations]
verify_jwt = false

[functions.generate-sitemap-images]
verify_jwt = false

[functions.blog-ssr]
verify_jwt = false

[functions.halaxy-auth]
verify_jwt = false

[functions.halaxy-api]
verify_jwt = true