'use client';

import Head from "next/head";
import { useState } from 'react';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { OptimizedBackground } from '@/components/ui/optimized-background';
// Image served from /public/ for instant CDN loading
import { PageNavigation } from '@/components/navigation/PageNavigation';

// Utility functions for saving assessment results
const downloadResults = (assessmentType: string, score: number, maxScore: number, result: any, answers: any) => {
  const currentDate = new Date().toLocaleDateString('en-AU');
  const currentTime = new Date().toLocaleTimeString('en-AU');
  
  let content = `
DOWNSCALE WEIGHT LOSS CLINIC - MENTAL HEALTH ASSESSMENT RESULTS
===================================================

Assessment Type: ${assessmentType === 'BED' ? 'BEDS-7 Binge Eating Disorder Screening' : 'ASRS-v1.1 ADHD Screening'}
Completed: ${currentDate} at ${currentTime}
Score: ${score}/${maxScore}
Result: ${result.title}

ASSESSMENT SUMMARY:
${result.message}

DETAILED RESPONSES:
`;

  if (assessmentType === 'BED') {
    const questions = [
      'Do you often feel you can\'t control how much you eat?',
      'Do you eat unusually large amounts of food in a short time?',
      'Do you feel distressed, upset, or guilty after eating?',
      'Do you avoid social events due to fear of eating in front of others?',
      'Do you eat rapidly or secretly?',
      'Do you continue to eat even when you\'re full?',
      'Has your eating behaviour affected your physical health, relationships, or daily life?'
    ];
    
    Object.entries(answers).forEach(([key, value], index) => {
      content += `${index + 1}. ${questions[index]}\n   Answer: ${value === 'yes' ? 'Yes' : 'No'}\n\n`;
    });
  } else {
    const questions = [
      'How often do you have trouble wrapping up the final details of a project?',
      'How often do you have difficulty getting things in order when you have to do a task that requires organisation?',
      'How often do you have problems remembering appointments or obligations?',
      'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
      'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
      'How often do you feel overly active and compelled to do things, like you were driven by a motor?'
    ];
    
    Object.entries(answers).forEach(([key, value], index) => {
      const answerLabel = value === 'never' ? 'Never' : 
                         value === 'rarely' ? 'Rarely' : 
                         value === 'sometimes' ? 'Sometimes' : 
                         value === 'often' ? 'Often' : 'Very Often';
      content += `${index + 1}. ${questions[index]}\n   Answer: ${answerLabel}\n\n`;
    });
  }

  content += `
NEXT STEPS:
${assessmentType === 'BED' ? 
  `• Discuss these results with your GP
• Ask about an Eating Disorder Treatment and Management Plan
• Consider referral to a psychologist or dietitian
• Contact Downscale Weight Loss Clinic for support: https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131` :
  `• Share these results with your GP
• Request referral to a psychiatrist for full ADHD evaluation
• Consider a Mental Health Care Plan (MHCP)
• Contact Downscale Weight Loss Clinic for support: https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131`
}

IMPORTANT DISCLAIMER:
This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
Results should be discussed with a qualified healthcare professional.

Generated by Downscale Weight Loss Clinic - Professional Weight Management Support
Visit: https://www.downscale.com.au
`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Downscale-Weight-Loss-Clinic-${assessmentType}-Assessment-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const shareResults = (assessmentType: string, score: number, maxScore: number, result: any) => {
  const text = `I completed a ${assessmentType === 'BED' ? 'BEDS-7 Binge Eating Disorder' : 'ASRS-v1.1 ADHD'} assessment at Downscale Weight Loss Clinic.

Score: ${score}/${maxScore} - ${result.title}

This professional screening tool can help identify if further assessment may be beneficial. 

Learn more: https://www.downscale.com.au/mental-health-support`;

  if (navigator.share) {
    navigator.share({
      title: `${assessmentType} Assessment Results - Downscale Weight Loss Clinic`,
      text: text,
      url: 'https://www.downscale.com.au/mental-health-support'
    });
  } else {
    navigator.clipboard.writeText(text).then(() => {
      alert('Results copied to clipboard!');
    });
  }
};

const emailResults = (assessmentType: string, score: number, maxScore: number, result: any) => {
  const subject = `${assessmentType === 'BED' ? 'BEDS-7 Binge Eating Disorder' : 'ASRS-v1.1 ADHD'} Assessment Results`;
  const body = `Dear Doctor,

I have completed a ${assessmentType === 'BED' ? 'BEDS-7 Binge Eating Disorder screening' : 'ASRS-v1.1 ADHD screening'} questionnaire through Downscale Weight Loss Clinic.

Assessment Results:
- Score: ${score}/${maxScore}
- Result: ${result.title}
- Recommendation: ${result.message}

I would like to discuss these results with you and explore ${assessmentType === 'BED' ? 'whether I may benefit from an Eating Disorder Treatment and Management Plan under Medicare' : 'the possibility of a referral for formal ADHD evaluation'}.

The complete assessment details are attached/will be provided during our consultation.

Thank you for your time.

Best regards,
[Your Name]

Assessment completed via: https://www.downscale.com.au/mental-health-support`;

  window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
};

// BEDS-7 Assessment Component
function BedsAssessment() {
  const [answers, setAnswers] = useState({
    control: null,
    largeAmounts: null,
    distressed: null,
    avoidSocial: null,
    rapidSecret: null,
    continueEating: null,
    affectedLife: null
  });

  const [showResults, setShowResults] = useState(false);

  const questions = [
    {
      id: 'control',
      question: 'Do you often feel you can\'t control how much you eat?',
      category: 'Control over eating'
    },
    {
      id: 'largeAmounts',
      question: 'Do you eat unusually large amounts of food in a short time?',
      category: 'Binge episodes'
    },
    {
      id: 'distressed',
      question: 'Do you feel distressed, upset, or guilty after eating?',
      category: 'Emotional response'
    },
    {
      id: 'avoidSocial',
      question: 'Do you avoid social events due to fear of eating in front of others?',
      category: 'Social impact'
    },
    {
      id: 'rapidSecret',
      question: 'Do you eat rapidly or secretly?',
      category: 'Eating patterns'
    },
    {
      id: 'continueEating',
      question: 'Do you continue to eat even when you\'re full?',
      category: 'Satiety recognition'
    },
    {
      id: 'affectedLife',
      question: 'Has your eating behaviour affected your physical health, relationships, or daily life?',
      category: 'Life impact'
    }
  ];

  const handleAnswer = (questionId, answer) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const calculateScore = () => {
    return Object.values(answers).filter(answer => answer === 'yes').length;
  };

  const getResultMessage = (score) => {
    if (score >= 3) {
      return {
        title: 'Further Assessment Recommended',
        message: 'Your responses suggest you may benefit from professional assessment for Binge Eating Disorder. Consider discussing these results with your GP.',
        color: 'text-red-400',
        bgColor: 'bg-red-500/10',
        borderColor: 'border-red-500/30'
      };
    } else {
      return {
        title: 'Low Risk Indicated',
        message: 'Your responses suggest a lower likelihood of BED. However, if you have ongoing concerns about your eating patterns, consider speaking with a healthcare professional.',
        color: 'text-green-400',
        bgColor: 'bg-green-500/10',
        borderColor: 'border-green-500/30'
      };
    }
  };

  const allAnswered = Object.values(answers).every(answer => answer !== null);
  const score = calculateScore();
  const result = getResultMessage(score);

  return (
    <div className="bg-slate-800 rounded-xl p-8 border border-slate-700">
      <div className="mb-8">
        <h3 className="text-2xl font-bold text-cream mb-4">BEDS-7 Questionnaire</h3>
        <p className="text-cream opacity-80 mb-6">
          Please answer the following questions based on the past 3 months:
        </p>
      </div>

      <div className="space-y-6">
        {questions.map((q, index) => (
          <div key={q.id} className="bg-slate-900 rounded-lg p-6 border border-slate-600">
            <div className="mb-4">
              <span className="text-brown font-semibold text-sm">{q.category}</span>
              <h4 className="text-lg font-medium text-cream mt-1">
                {index + 1}. {q.question}
              </h4>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => handleAnswer(q.id, 'yes')}
                className={`px-6 py-4 rounded-lg font-medium transition-all text-base ${
                  answers[q.id] === 'yes'
                    ? 'bg-brown text-white shadow-lg'
                    : 'bg-slate-700 text-cream hover:bg-slate-600 active:bg-slate-500'
                }`}
              >
                Yes
              </button>
              <button
                onClick={() => handleAnswer(q.id, 'no')}
                className={`px-6 py-4 rounded-lg font-medium transition-all text-base ${
                  answers[q.id] === 'no'
                    ? 'bg-brown text-white shadow-lg'
                    : 'bg-slate-700 text-cream hover:bg-slate-600 active:bg-slate-500'
                }`}
              >
                No
              </button>
            </div>
          </div>
        ))}
      </div>

      {allAnswered && (
        <div className="mt-8">
          <button
            onClick={() => setShowResults(!showResults)}
            className="w-full bg-brown hover:bg-brown/90 text-white font-bold py-4 px-6 rounded-lg transition-colors"
          >
            {showResults ? 'Hide Results' : 'Show My Results'}
          </button>
        </div>
      )}

      {showResults && allAnswered && (
        <div className={`mt-6 p-6 rounded-lg border ${result.bgColor} ${result.borderColor}`}>
          <div className="text-center">
            <h4 className={`text-xl font-bold ${result.color} mb-2`}>
              Score: {score}/7 - {result.title}
            </h4>
            <p className="text-cream opacity-90 mb-6">
              {result.message}
            </p>
            
            <div className="bg-slate-900/50 rounded-lg p-4 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Next Steps if Assessment Suggests BED:</h5>
              <ul className="text-left space-y-2 text-cream opacity-80 text-sm">
                <li>• Print or screenshot your responses</li>
                <li>• Book an appointment with your GP</li>
                <li>• Discuss whether you may qualify for an <strong>Eating Disorder Treatment and Management Plan</strong> under Medicare</li>
                <li>• If eligible, receive up to <strong>40 sessions</strong> with a psychologist, dietitian, or other allied health professional</li>
              </ul>
            </div>

            {/* Save Results Feature */}
            <div className="bg-slate-900/50 rounded-lg p-4 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Save Your Results</h5>
              <div className="flex flex-wrap gap-3 justify-center">
                <button
                  onClick={() => downloadResults('BED', score, 7, result, answers)}
                  className="px-4 py-2 bg-brown/20 text-brown border border-brown/30 rounded-lg hover:bg-brown/30 transition-colors text-sm font-medium"
                >
                  📄 Download Report
                </button>
                <button
                  onClick={() => shareResults('BED', score, 7, result)}
                  className="px-4 py-2 bg-blue/20 text-blue border border-blue/30 rounded-lg hover:bg-blue/30 transition-colors text-sm font-medium"
                >
                  📱 Share Results
                </button>
                <button
                  onClick={() => emailResults('BED', score, 7, result)}
                  className="px-4 py-2 bg-green/20 text-green border border-green/30 rounded-lg hover:bg-green/30 transition-colors text-sm font-medium"
                >
                  ✉️ Email to GP
                </button>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-slate-600">
              <p className="text-sm text-cream opacity-70 mb-4">
                <strong>Important:</strong> This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
                At Downscale, we offer non-judgmental, evidence-based support and can help with GP discussions or referrals.
              </p>
              <div className="flex justify-center">
                <a 
                  href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center bg-brown text-white px-8 py-3 rounded-lg hover:bg-brown/80 transition-colors font-medium"
                >
                  <i className="fas fa-calendar-check mr-2"></i>
                  Book BED Support Consultation
                </a>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ADHD ASRS Assessment Component
function AdhdAssessment() {
  const [answers, setAnswers] = useState({
    trouble_wrapping: null,
    difficulty_organising: null,
    problems_remembering: null,
    avoid_requiring_thinking: null,
    fidget_restless: null,
    feel_overly_active: null
  });

  const [showResults, setShowResults] = useState(false);

  const questions = [
    {
      id: 'trouble_wrapping',
      question: 'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
      category: 'Task completion'
    },
    {
      id: 'difficulty_organising',
      question: 'How often do you have difficulty getting things in order when you have to do a task that requires organisation?',
      category: 'Organisation'
    },
    {
      id: 'problems_remembering',
      question: 'How often do you have problems remembering appointments or obligations?',
      category: 'Memory'
    },
    {
      id: 'avoid_requiring_thinking',
      question: 'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
      category: 'Task initiation'
    },
    {
      id: 'fidget_restless',
      question: 'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
      category: 'Hyperactivity'
    },
    {
      id: 'feel_overly_active',
      question: 'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
      category: 'Internal restlessness'
    }
  ];

  const answerOptions = [
    { value: 'never', label: 'Never', score: 0 },
    { value: 'rarely', label: 'Rarely', score: 1 },
    { value: 'sometimes', label: 'Sometimes', score: 2 },
    { value: 'often', label: 'Often', score: 3 },
    { value: 'very_often', label: 'Very Often', score: 4 }
  ];

  const handleAnswer = (questionId, answer) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const calculateScore = () => {
    return Object.values(answers).filter(answer => answer === 'often' || answer === 'very_often').length;
  };

  const getResultMessage = (score) => {
    if (score >= 4) {
      return {
        title: 'ADHD Assessment Recommended',
        message: 'Your responses suggest you may benefit from a full ADHD evaluation with a psychiatrist. These results can be shared with your GP for a referral.',
        color: 'text-red-400',
        bgColor: 'bg-red-500/10',
        borderColor: 'border-red-500/30'
      };
    } else {
      return {
        title: 'Lower Likelihood of ADHD',
        message: 'Your responses suggest a lower likelihood of ADHD. However, if you continue to have concerns about attention, focus, or hyperactivity, consider discussing with a healthcare professional.',
        color: 'text-green-400',
        bgColor: 'bg-green-500/10',
        borderColor: 'border-green-500/30'
      };
    }
  };

  const allAnswered = Object.values(answers).every(answer => answer !== null);
  const score = calculateScore();
  const result = getResultMessage(score);

  return (
    <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
      <div className="mb-8">
        <h3 className="text-2xl font-bold text-cream mb-4">ASRS-v1.1 Part A Screening</h3>
        <p className="text-cream opacity-80 mb-6">
          Please answer how often each statement applies to you over the past 6 months:
        </p>
      </div>

      <div className="space-y-6">
        {questions.map((q, index) => (
          <div key={q.id} className="bg-slate-800 rounded-lg p-6 border border-slate-600">
            <div className="mb-4">
              <span className="text-brown font-semibold text-sm">{q.category}</span>
              <h4 className="text-lg font-medium text-cream mt-1">
                {index + 1}. {q.question}
              </h4>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-2">
              {answerOptions.map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleAnswer(q.id, option.value)}
                  className={`px-4 py-3 rounded-lg font-medium transition-all text-sm ${
                    answers[q.id] === option.value
                      ? 'bg-brown text-white shadow-lg'
                      : 'bg-slate-700 text-cream hover:bg-slate-600'
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      {allAnswered && (
        <div className="mt-8">
          <button
            onClick={() => setShowResults(!showResults)}
            className="w-full bg-brown hover:bg-brown/90 text-white font-bold py-4 px-6 rounded-lg transition-colors"
          >
            {showResults ? 'Hide Results' : 'Show My Results'}
          </button>
        </div>
      )}

      {showResults && allAnswered && (
        <div className={`mt-6 p-6 rounded-lg border ${result.bgColor} ${result.borderColor}`}>
          <div className="text-center">
            <h4 className={`text-xl font-bold ${result.color} mb-2`}>
              Positive Responses: {score}/6 - {result.title}
            </h4>
            <p className="text-cream opacity-90 mb-6">
              {result.message}
            </p>
            
            <div className="bg-slate-800/50 rounded-lg p-4 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Common Signs of ADHD in Adults:</h5>
              <ul className="text-left space-y-2 text-cream opacity-80 text-sm">
                <li>• Difficulty focusing on tasks</li>
                <li>• Forgetfulness and disorganisation</li>
                <li>• Trouble following through with goals</li>
                <li>• Easily distracted</li>
                <li>• Emotional reactivity or mood swings</li>
              </ul>
            </div>

            <div className="bg-slate-800/50 rounded-lg p-4 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Next Steps if Assessment Suggests ADHD:</h5>
              <ul className="text-left space-y-2 text-cream opacity-80 text-sm">
                <li>• Print or email your ASRS results</li>
                <li>• Discuss them with your GP for a referral to a psychiatrist</li>
                <li>• Ask if a Mental Health Care Plan (MHCP) is suitable</li>
                <li>• Australian psychiatrists often request this specific assessment before formal evaluation</li>
              </ul>
            </div>

            {/* Save Results Feature */}
            <div className="bg-slate-800/50 rounded-lg p-4 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Save Your Results</h5>
              <div className="flex flex-wrap gap-3 justify-center">
                <button
                  onClick={() => downloadResults('ADHD', score, 6, result, answers)}
                  className="px-4 py-2 bg-brown/20 text-brown border border-brown/30 rounded-lg hover:bg-brown/30 transition-colors text-sm font-medium"
                >
                  📄 Download Report
                </button>
                <button
                  onClick={() => shareResults('ADHD', score, 6, result)}
                  className="px-4 py-2 bg-blue/20 text-blue border border-blue/30 rounded-lg hover:bg-blue/30 transition-colors text-sm font-medium"
                >
                  📱 Share Results
                </button>
                <button
                  onClick={() => emailResults('ADHD', score, 6, result)}
                  className="px-4 py-2 bg-green/20 text-green border border-green/30 rounded-lg hover:bg-green/30 transition-colors text-sm font-medium"
                >
                  ✉️ Email to GP
                </button>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-slate-600">
              <p className="text-sm text-cream opacity-70 mb-4">
                <strong>Important:</strong> This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
                At Downscale, we understand how complex ADHD can be and offer non-judgmental support and appropriate referrals.
              </p>
              <div className="flex justify-center">
                <a 
                  href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center bg-brown text-white px-8 py-3 rounded-lg hover:bg-brown/80 transition-colors font-medium"
                >
                  <i className="fas fa-calendar-check mr-2"></i>
                  Book ADHD Support Consultation
                </a>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function MentalHealthSupport() {
  const mentalHealthPillars = [
    {
      icon: "🪞",
      title: "Body Image Transformation",
      description: "Developing a healthy relationship with your changing body",
      features: ["Body acceptance strategies", "Mirror work techniques", "Self-compassion practices", "Realistic expectation setting"],
      color: "bg-purple-600"
    },
    {
      icon: "🍽️",
      title: "Emotional Eating Support",
      description: "Understanding and managing food-emotion connections",
      features: ["Trigger identification", "Alternative coping strategies", "Mindful eating practices", "Stress response management"],
      color: "bg-blue-600"
    },
    {
      icon: "💭",
      title: "Mindset Transformation",
      description: "Shifting mental patterns for sustainable change",
      features: ["Limiting belief identification", "Positive self-talk development", "Growth mindset cultivation", "Resilience building"],
      color: "bg-green-600"
    },
    {
      icon: "💕",
      title: "Relationships & Intimacy",
      description: "How weight loss transforms your relationships and intimate connections",
      features: ["Confidence in relationships", "Intimacy improvements", "Partner communication", "Social dynamics shifts"],
      color: "bg-pink-600"
    },
    {
      icon: "🎯",
      title: "Goal Setting Psychology",
      description: "Real-world goal setting based on Maslow's hierarchy and authentic motivation",
      features: ["Maslow-based goal hierarchy", "Authentic motivation discovery", "Realistic milestone setting", "Progress celebration"],
      color: "bg-orange-600"
    }
  ];

  const psychologicalStages = [
    {
      stage: "Pre-Contemplation",
      description: "Building awareness and motivation",
      focus: ["Understanding health risks", "Identifying personal motivators", "Exploring benefits of change", "Addressing ambivalence"],
      duration: "Weeks to months"
    },
    {
      stage: "Preparation", 
      description: "Planning and mindset preparation",
      focus: ["Setting realistic expectations", "Building confidence", "Creating support systems", "Developing coping strategies"],
      duration: "2-4 weeks"
    },
    {
      stage: "Action",
      description: "Active change implementation",
      focus: ["Managing initial challenges", "Celebrating small wins", "Adjusting to new routines", "Handling setbacks"],
      duration: "3-6 months"
    },
    {
      stage: "Maintenance",
      description: "Long-term psychological adaptation",
      focus: ["Identity integration", "Ongoing motivation", "Relapse prevention", "Lifestyle satisfaction"],
      duration: "Ongoing"
    }
  ];

  const stressManagement = [
    {
      technique: "Stress-Eating Cycle Breaking",
      description: "Interrupt the automatic stress-to-food response",
      icon: "🔄",
      strategies: ["HALT check (Hungry, Angry, Lonely, Tired)", "5-minute delay technique", "Alternative comfort activities", "Breathing exercises"]
    },
    {
      technique: "Cortisol Management",
      description: "Reduce stress hormone impact on weight",
      icon: "⚡",
      strategies: ["Regular sleep schedule", "Mindfulness practices", "Physical activity", "Social connection"]
    },
    {
      technique: "Perfectionism Management",
      description: "Develop healthy progress expectations",
      icon: "🎯",
      strategies: ["Progress over perfection mindset", "Flexible goal setting", "Self-compassion practices", "Learning from setbacks"]
    },
    {
      technique: "Social Support Building",
      description: "Create positive environmental influences",
      icon: "👥",
      strategies: ["Supportive relationship cultivation", "Boundary setting with food pushers", "Community engagement", "Professional support networks"]
    }
  ];

  return (
    <>
      <Head>
        <title>Mental Health & Psychology Support | Weight Loss Mindset | Downscale Weight Loss Clinic</title>
        <meta name="description" content="Professional psychological support for weight loss. Address body image, emotional eating, stress management, and develop sustainable mindset changes for long-term success." />
        <meta name="keywords" content="weight loss psychology Australia, emotional eating support, body image therapy, stress management, mindset coaching, mental health telehealth" />
        <link rel="canonical" href="https://www.downscale.com.au/mental-health-support" />
        
        <meta property="og:title" content="Mental Health & Psychology Support | Weight Loss Mindset" />
        <meta property="og:description" content="Professional psychological support addressing the mental aspects of weight management and body image." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.downscale.com.au/mental-health-support" />
        
        <script type="application/ld+json">
          {`
            {
              "@context": "https://schema.org",
              "@type": "MedicalWebPage",
              "name": "Mental Health & Psychology Support",
              "description": "Psychological support services for weight management including body image, emotional eating, and mindset transformation",
              "publisher": {
                "@type": "Organization",
                "name": "Downscale Weight Loss Clinic"
              }
            }
          `}
        </script>
      </Head>
      <Header />
      <main className="min-h-screen bg-slate-900">
        {/* Hero Section */}
        <div 
          className="relative min-h-[60vh] flex items-center justify-center overflow-hidden"
          style={{
            backgroundImage: "url(/mental-health-hero.jpg)",
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat'
          }}
        >
          <img 
            src="/mental-health-hero.jpg" 
            alt="" 
            className="hidden" 
            loading="eager"
          />
          <div className="container mx-auto px-4 relative z-10">
            <div className="max-w-4xl mx-auto text-center">
              <h1
                className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6"
                style={{ color: '#f7f2d3', textShadow: '3px 3px 6px rgba(0,0,0,0.9), 1px 1px 3px rgba(0,0,0,0.8)' }}
              >
                Mental Health & Weight Loss Support
              </h1>
              <div className="w-20 h-1 bg-cream/80 mx-auto mb-6"></div>
              <p 
                className="text-xl md:text-2xl mb-8 max-w-3xl mx-auto"
                style={{ color: '#f7f2d3', textShadow: '2px 2px 4px rgba(0,0,0,0.9), 1px 1px 2px rgba(0,0,0,0.8)' }}
              >
                Evidence-based psychological support for sustainable weight management - addressing ADHD, Binge Eating Disorder, and emotional eating patterns
              </p>
              <a 
                href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-brown hover:bg-brown/90 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-colors shadow-xl hover-scale animate-fade-in"
              >
                <i className="fas fa-heart mr-3"></i>
                Book Appointment
                <i className="fas fa-arrow-right ml-3"></i>
              </a>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-4 py-2">
          <PageNavigation />
        </div>

        {/* Why Psychology Matters */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Why Psychology is Crucial for Weight Loss
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Weight and wellbeing don't happen in a vacuum. Mental health, stress, emotions, and mindset 
                significantly influence your weight management journey.
              </p>
            </div>

            <div className="max-w-5xl mx-auto">
              <div className="grid md:grid-cols-3 gap-8 text-center">
                <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
                  <i className="fas fa-brain text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Neural Pathways</h3>
                  <p className="text-cream opacity-80 text-sm">
                    Established thought patterns and habits require conscious rewiring for lasting change
                  </p>
                </div>
                <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
                  <i className="fas fa-heartbeat text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Stress Response</h3>
                  <p className="text-cream opacity-80 text-sm">
                    Cortisol and stress hormones directly impact metabolism and food cravings
                  </p>
                </div>
                <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
                  <i className="fas fa-users text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Social Factors</h3>
                  <p className="text-cream opacity-80 text-sm">
                    Relationships, environment, and social dynamics influence eating behaviors
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Core Mental Health Support */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Comprehensive Psychological Support
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
            </div>

            <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto">
              {mentalHealthPillars.map((pillar, index) => (
                <div
                  key={index}
                  className="bg-slate-800 rounded-xl p-8 hover:bg-slate-750 transition-colors border border-slate-700"
                >
                  <div className="flex items-start mb-6">
                    <div className="text-4xl mr-4">{pillar.icon}</div>
                    <div>
                      <h3 className="text-2xl font-bold text-cream mb-2">{pillar.title}</h3>
                      <p className="text-cream opacity-80 mb-4">{pillar.description}</p>
                    </div>
                  </div>
                  
                  <ul className="space-y-3">
                    {pillar.features.map((feature, featureIndex) => (
                      <li
                        key={featureIndex}
                        className="flex items-start text-cream opacity-70"
                      >
                        <i className="fas fa-check text-brown mr-3 mt-1"></i>
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Psychological Stages */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Stages of Psychological Change
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Understanding where you are in the change process helps us provide targeted psychological support
              </p>
            </div>

            <div className="max-w-6xl mx-auto">
              <div className="grid md:grid-cols-2 gap-8">
                {psychologicalStages.map((stage, index) => (
                  <div
                    key={index}
                    className="bg-slate-900 rounded-xl p-8 border border-slate-700"
                  >
                    <div className="flex items-center mb-4">
                      <div className="w-8 h-8 bg-brown rounded-full flex items-center justify-center mr-4">
                        <span className="text-white font-bold text-sm">{index + 1}</span>
                      </div>
                      <div>
                        <h3 className="text-xl font-bold text-cream">{stage.stage}</h3>
                        <p className="text-cream opacity-60 text-sm">{stage.duration}</p>
                      </div>
                    </div>
                    <p className="text-cream opacity-80 mb-4">{stage.description}</p>
                    <div>
                      <h4 className="text-lg font-semibold text-cream mb-3">Focus Areas:</h4>
                      <ul className="space-y-2">
                        {stage.focus.map((item, itemIndex) => (
                          <li key={itemIndex} className="text-cream opacity-70 text-sm">
                            <i className="fas fa-arrow-right text-brown mr-2"></i>
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Stress Management Techniques */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Stress Management & Coping Strategies
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Practical techniques to manage stress, reduce emotional eating, and build psychological resilience
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto">
              {stressManagement.map((technique, index) => (
                <div
                  key={index}
                  className="bg-slate-800 rounded-xl p-8 hover:bg-slate-750 transition-colors border border-slate-700"
                >
                  <div className="flex items-start mb-6">
                    <div className="text-4xl mr-4">{technique.icon}</div>
                    <div>
                      <h3 className="text-2xl font-bold text-cream mb-2">{technique.technique}</h3>
                      <p className="text-cream opacity-80 mb-4">{technique.description}</p>
                    </div>
                  </div>
                  
                  <ul className="space-y-3">
                    {technique.strategies.map((strategy, strategyIndex) => (
                      <li
                        key={strategyIndex}
                        className="flex items-start text-cream opacity-70"
                      >
                        <i className="fas fa-lightbulb text-brown mr-3 mt-1"></i>
                        {strategy}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Mindset Transformation */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <div className="text-center mb-12">
                <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                  From Diet Mindset to Lifestyle Transformation
                </h2>
                <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              </div>

              <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
                <div className="grid md:grid-cols-2 gap-8">
                  <div>
                    <h3 className="text-xl font-bold text-red-400 mb-4">❌ Diet Mindset</h3>
                    <ul className="space-y-3">
                      <li className="text-cream opacity-70">All-or-nothing thinking</li>
                      <li className="text-cream opacity-70">Restriction and deprivation</li>
                      <li className="text-cream opacity-70">Short-term focus</li>
                      <li className="text-cream opacity-70">External motivation only</li>
                      <li className="text-cream opacity-70">Perfectionism expectations</li>
                      <li className="text-cream opacity-70">Self-criticism and guilt</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-green-400 mb-4">✅ Lifestyle Mindset</h3>
                    <ul className="space-y-3">
                      <li className="text-cream opacity-70">Flexible, balanced approach</li>
                      <li className="text-cream opacity-70">Sustainable habits</li>
                      <li className="text-cream opacity-70">Long-term health focus</li>
                      <li className="text-cream opacity-70">Internal motivation and values</li>
                      <li className="text-cream opacity-70">Progress over perfection</li>
                      <li className="text-cream opacity-70">Self-compassion and learning</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* BED Self-Assessment Tool */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                BEDS-7 Binge Eating Disorder Assessment
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-80 text-lg max-w-3xl mx-auto">
                Binge Eating Disorder is one of the most common eating disorders but is often missed or misunderstood. 
                This validated screening tool helps identify if you may benefit from further assessment.
              </p>
            </div>

            <div className="max-w-4xl mx-auto">
              <BedsAssessment />
            </div>
          </div>
        </section>

        {/* ADHD Self-Assessment Tool */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                ASRS ADHD Self-Assessment (Part A)
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-80 text-lg max-w-3xl mx-auto">
                ADHD is a neurodevelopmental condition that can affect attention, organisation, focus, emotional regulation and self-esteem. 
                This is the screening tool often requested by Australian psychiatrists before formal assessment.
              </p>
            </div>

            <div className="max-w-4xl mx-auto">
              <AdhdAssessment />
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="bg-brown/10 rounded-xl p-8 max-w-4xl mx-auto text-center border border-brown/20">
              <h2 className="text-3xl font-bold text-cream mb-4">
                Ready to Transform Your Mindset?
              </h2>
              <p className="text-cream opacity-90 text-lg mb-6">
                Get professional psychological support to address the mental and emotional aspects of weight management
              </p>
              <a 
                href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-brown hover:bg-brown/90 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-colors"
              >
                <i className="fas fa-hand-holding-heart mr-3"></i>
                Start Your Mental Health Journey
              </a>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}