'use client';

import Head from "next/head";
import { useState } from 'react';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { supabase } from '@/integrations/supabase/client';
import { OptimizedBackground } from '@/components/ui/optimized-background';
// Image served from /public/ for instant CDN loading
import { PageNavigation } from '@/components/navigation/PageNavigation';

// Utility functions for saving assessment results
const downloadSleepResults = (assessmentType: string, score: number, maxScore: number, result: any, answers: any) => {
  // Use ISO format to prevent hydration issues
  const now = new Date();
  const currentDate = now.toISOString().split('T')[0];
  const currentTime = now.toISOString().split('T')[1].split('.')[0];
  
  let content = `
DOWNSCALE WEIGHT LOSS CLINIC - SLEEP ASSESSMENT RESULTS
==========================================

Assessment Type: ${assessmentType}
Completed: ${currentDate} at ${currentTime}
Score: ${score}/${maxScore}
Result: ${result.risk || result.title}

ASSESSMENT SUMMARY:
${result.recommendation || result.message}

DETAILED RESPONSES:
`;

  if (assessmentType === 'STOP-BANG Sleep Apnea Screening') {
    const questions = [
      'Do you SNORE loudly?',
      'Do you often feel TIRED, fatigued, or sleepy during daytime?',
      'Has anyone OBSERVED you stop breathing during your sleep?',
      'Do you have or are you being treated for high blood PRESSURE?',
      'BMI more than 35 kg/m²?',
      'AGE over 50 years old?',
      'NECK circumference greater than 40cm?',
      'GENDER: Are you male?'
    ];
    
    Object.entries(answers).forEach(([key, value], index) => {
      content += `${index + 1}. ${questions[index]}\n   Answer: ${value ? 'Yes' : 'No'}\n\n`;
    });
  } else {
    const questions = [
      'Sitting and reading',
      'Watching TV',
      'Sitting, inactive in a public place',
      'As a passenger in a car for an hour without a break',
      'Lying down to rest in the afternoon when circumstances permit',
      'Sitting and talking to someone',
      'Sitting quietly after a lunch without alcohol',
      'In a car, while stopped for a few minutes in traffic'
    ];
    
    Object.entries(answers).forEach(([key, value], index) => {
      const answerLabel = value === 0 ? 'Would never doze' : 
                         value === 1 ? 'Slight chance of dozing' : 
                         value === 2 ? 'Moderate chance of dozing' : 'High chance of dozing';
      content += `${index + 1}. ${questions[index]}\n   Answer: ${answerLabel} (${value} points)\n\n`;
    });
  }

  content += `
NEXT STEPS:
${assessmentType === 'STOP-BANG Sleep Apnea Screening' ? 
  `• Share these results with your GP or sleep specialist
• Consider referral for comprehensive sleep study if high risk
• Discuss CPAP therapy options if sleep apnea is confirmed
• Implement weight management strategies
• Contact Downscale Weight Loss Clinic for integrated care: https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131` :
  `• Discuss these results with your healthcare provider
• Consider sleep study evaluation if excessive daytime sleepiness
• Evaluate for underlying sleep disorders
• Implement sleep hygiene improvements
• Contact Downscale Weight Loss Clinic for comprehensive sleep optimisation: https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131`
}

IMPORTANT DISCLAIMER:
This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
Results should be discussed with a qualified healthcare professional.

Generated by Downscale Weight Loss Clinic - Professional Weight Management & Sleep Optimisation
Visit: https://www.downscale.com.au
Phone: (Contact via website)
`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Downscale-Weight-Loss-Clinic-${assessmentType.replace(/\s+/g, '-')}-Assessment-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const shareSleepResults = (assessmentType: string, score: number, maxScore: number, result: any) => {
  const text = `I completed a ${assessmentType} at Downscale Weight Loss Clinic.

Score: ${score}/${maxScore} - ${result.risk || result.title}

This professional screening tool helps identify sleep-related issues that may be affecting my health and weight management goals.

Learn more: https://www.downscale.com.au/sleep-recovery-optimisation`;

  if (navigator.share) {
    navigator.share({
      title: `${assessmentType} Results - Downscale Weight Loss Clinic`,
      text: text,
      url: 'https://www.downscale.com.au/sleep-recovery-optimisation'
    });
  } else {
    navigator.clipboard.writeText(text).then(() => {
      alert('Results copied to clipboard!');
    });
  }
};

const emailSleepResults = (assessmentType: string, score: number, maxScore: number, result: any) => {
  const subject = `${assessmentType} Results`;
  const body = `Dear Doctor,

I have completed a ${assessmentType} questionnaire through Downscale Weight Loss Clinic.

Assessment Results:
- Score: ${score}/${maxScore}
- Result: ${result.risk || result.title}
- Recommendation: ${result.recommendation || result.message}

I would like to discuss these results with you and explore appropriate next steps for evaluation and management.

The complete assessment details are attached/will be provided during our consultation.

Thank you for your time.

Best regards,
[Your Name]

Assessment completed via: https://www.downscale.com.au/sleep-recovery-optimisation`;

  window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
};

// AI Analysis function
const getAIAnalysis = async (assessmentType: string, score: number, answers: any) => {
  try {
    const response = await supabase.functions.invoke('sleep-ai-analysis', {
      body: {
        assessmentType,
        score,
        answers
      }
    });

    if (response.error) {
      throw new Error(response.error.message);
    }

    return response.data.analysis;
  } catch (error) {
    console.error('AI Analysis Error:', error);
    return 'AI analysis temporarily unavailable. Please consult with a healthcare professional for detailed interpretation.';
  }
};

// STOP-BANG Assessment Component
function StopBangAssessment() {
  const [answers, setAnswers] = useState({
    snoring: null,
    tired: null,
    observed: null,
    pressure: null,
    bmi: null,
    age: null,
    neck: null,
    gender: null
  });

  const [showResults, setShowResults] = useState(false);

  const questions = [
    {
      id: 'snoring',
      question: 'Do you SNORE loudly (louder than talking or loud enough to be heard through closed doors)?',
      category: 'S - Snoring'
    },
    {
      id: 'tired',
      question: 'Do you often feel TIRED, fatigued, or sleepy during daytime?',
      category: 'T - Tired'
    },
    {
      id: 'observed',
      question: 'Has anyone OBSERVED you stop breathing during your sleep?',
      category: 'O - Observed'
    },
    {
      id: 'pressure',
      question: 'Do you have or are you being treated for high blood PRESSURE?',
      category: 'P - Pressure'
    },
    {
      id: 'bmi',
      question: 'BMI more than 35 kg/m²?',
      category: 'B - BMI'
    },
    {
      id: 'age',
      question: 'AGE over 50 years old?',
      category: 'A - Age'
    },
    {
      id: 'neck',
      question: 'NECK circumference greater than 40cm (16 inches)?',
      category: 'N - Neck'
    },
    {
      id: 'gender',
      question: 'GENDER: Are you male?',
      category: 'G - Gender'
    }
  ];

  const handleAnswer = (questionId, answer) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const calculateScore = () => {
    return Object.values(answers).filter(answer => answer === true).length;
  };

  const getAssessment = (score) => {
    if (score >= 5) {
      return {
        risk: 'High Risk',
        color: 'text-red-400',
        bgColor: 'bg-red-900/20 border-red-400/30',
        recommendation: 'Strong recommendation for sleep study evaluation. High probability of moderate-severe OSA.',
        action: 'Book a consultation for immediate assessment and referral for sleep study.'
      };
    } else if (score >= 3) {
      return {
        risk: 'Intermediate Risk',
        color: 'text-yellow-400',
        bgColor: 'bg-yellow-900/20 border-yellow-400/30',
        recommendation: 'Moderate probability of OSA. Clinical evaluation recommended.',
        action: 'Discuss symptoms with your healthcare provider for further assessment.'
      };
    } else {
      return {
        risk: 'Low Risk',
        color: 'text-green-400',
        bgColor: 'bg-green-900/20 border-green-400/30',
        recommendation: 'Low probability of OSA. Continue good sleep hygiene practices.',
        action: 'Maintain healthy sleep habits and monitor for any changes in symptoms.'
      };
    }
  };

  const allAnswered = Object.values(answers).every(answer => answer !== null);
  const score = calculateScore();
  const assessment = getAssessment(score);

  return (
    <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
      <div className="space-y-6">
        {questions.map((q) => (
          <div key={q.id} className="border-b border-slate-700 pb-6">
            <div className="mb-4">
              <h4 className="text-brown font-semibold text-lg mb-2">{q.category}</h4>
              <p className="text-cream text-base">{q.question}</p>
            </div>
            <div className="flex space-x-4">
              <button
                onClick={() => handleAnswer(q.id, true)}
                className={`px-6 py-3 rounded-lg font-medium transition-colours ${
                  answers[q.id] === true
                    ? 'bg-brown text-white'
                    : 'bg-slate-800 text-cream hover:bg-slate-700'
                }`}
              >
                Yes
              </button>
              <button
                onClick={() => handleAnswer(q.id, false)}
                className={`px-6 py-3 rounded-lg font-medium transition-colours ${
                  answers[q.id] === false
                    ? 'bg-brown text-white'
                    : 'bg-slate-800 text-cream hover:bg-slate-700'
                }`}
              >
                No
              </button>
            </div>
          </div>
        ))}
      </div>

      {allAnswered && (
        <div className="mt-8 pt-8 border-t border-slate-700">
          <div className={`p-6 rounded-lg border ${assessment.bgColor}`}>
            <div className="text-center mb-6">
              <h3 className="text-2xl font-bold text-cream mb-2">
                Your STOP-BANG Score: {score}/8
              </h3>
              <div className={`text-xl font-semibold ${assessment.color}`}>
                {assessment.risk}
              </div>
            </div>
            
            <div className="space-y-4 text-cream">
              <p className="text-lg">
                <strong>Assessment:</strong> {assessment.recommendation}
              </p>
              <p className="text-base opacity-80">
                <strong>Recommended Action:</strong> {assessment.action}
              </p>
            </div>

            {/* Save Results Feature */}
            <div className="bg-slate-800/50 rounded-lg p-4 mt-6 mb-6">
              <h5 className="text-lg font-semibold text-cream mb-3">Save Your Results</h5>
              <div className="flex flex-wrap gap-3 justify-center">
                <button
                  onClick={() => downloadSleepResults('STOP-BANG Sleep Apnea Screening', score, 8, assessment, answers)}
                  className="px-4 py-2 bg-brown/20 text-brown border border-brown/30 rounded-lg hover:bg-brown/30 transition-colors text-sm font-medium"
                >
                  📄 Download Report
                </button>
                <button
                  onClick={() => shareSleepResults('STOP-BANG Sleep Apnea Screening', score, 8, assessment)}
                  className="px-4 py-2 bg-blue/20 text-blue border border-blue/30 rounded-lg hover:bg-blue/30 transition-colors text-sm font-medium"
                >
                  📱 Share Results
                </button>
                <button
                  onClick={() => emailSleepResults('STOP-BANG Sleep Apnea Screening', score, 8, assessment)}
                  className="px-4 py-2 bg-green/20 text-green border border-green/30 rounded-lg hover:bg-green/30 transition-colors text-sm font-medium"
                >
                  ✉️ Email to GP
                </button>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-slate-600">
              <p className="text-sm text-cream opacity-70 mb-4">
                <strong>Important:</strong> This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
                If you have concerns about sleep apnea, please consult with a healthcare provider.
              </p>
              <div className="flex justify-center">
                <a 
                  href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center bg-brown text-white px-8 py-3 rounded-lg hover:bg-brown/80 transition-colors font-medium"
                >
                  <i className="fas fa-calendar-check mr-2"></i>
                  Book Sleep Assessment Consultation
                </a>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Epworth Sleepiness Scale Assessment Component
function EpworthSleepinessScale() {
  const [answers, setAnswers] = useState({
    reading: null,
    watching_tv: null,
    sitting_inactive: null,
    passenger_car: null,
    lying_down: null,
    sitting_talking: null,
    after_lunch: null,
    car_traffic: null
  });

  const [showResults, setShowResults] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState('');
  const [loadingAI, setLoadingAI] = useState(false);

  const questions = [
    {
      id: 'reading',
      question: 'Sitting and reading',
      scenario: 'How likely are you to doze off or fall asleep while sitting and reading?'
    },
    {
      id: 'watching_tv',
      question: 'Watching TV',
      scenario: 'How likely are you to doze off or fall asleep while watching TV?'
    },
    {
      id: 'sitting_inactive',
      question: 'Sitting, inactive in a public place',
      scenario: 'How likely are you to doze off or fall asleep while sitting inactive in a public place (e.g., a theatre or a meeting)?'
    },
    {
      id: 'passenger_car',
      question: 'As a passenger in a car for an hour without a break',
      scenario: 'How likely are you to doze off or fall asleep as a passenger in a car for an hour without a break?'
    },
    {
      id: 'lying_down',
      question: 'Lying down to rest in the afternoon when circumstances permit',
      scenario: 'How likely are you to doze off or fall asleep when lying down to rest in the afternoon when circumstances permit?'
    },
    {
      id: 'sitting_talking',
      question: 'Sitting and talking to someone',
      scenario: 'How likely are you to doze off or fall asleep while sitting and talking to someone?'
    },
    {
      id: 'after_lunch',
      question: 'Sitting quietly after a lunch without alcohol',
      scenario: 'How likely are you to doze off or fall asleep while sitting quietly after a lunch without alcohol?'
    },
    {
      id: 'car_traffic',
      question: 'In a car, while stopped for a few minutes in the traffic',
      scenario: 'How likely are you to doze off or fall asleep in a car, while stopped for a few minutes in the traffic?'
    }
  ];

  const answerOptions = [
    { value: 0, label: 'Would never doze', description: 'No chance of dozing' },
    { value: 1, label: 'Slight chance of dozing', description: 'Slight chance' },
    { value: 2, label: 'Moderate chance of dozing', description: 'Moderate chance' },
    { value: 3, label: 'High chance of dozing', description: 'High chance' }
  ];

  const handleAnswer = (questionId: string, answer: number) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const calculateScore = () => {
    return Object.values(answers).reduce((sum, value) => sum + (value || 0), 0);
  };

  const getAssessment = (score: number) => {
    if (score >= 16) {
      return {
        title: 'Severe Excessive Daytime Sleepiness',
        color: 'text-red-400',
        bgColor: 'bg-red-900/20 border-red-400/30',
        message: 'Your score suggests severe excessive daytime sleepiness that may significantly impact your daily functioning.',
        recommendation: 'Immediate medical evaluation recommended. This level of sleepiness may indicate a serious sleep disorder requiring professional assessment.',
        action: 'Book urgent consultation for comprehensive sleep evaluation and possible sleep study referral.'
      };
    } else if (score >= 11) {
      return {
        title: 'Moderate Excessive Daytime Sleepiness', 
        color: 'text-orange-400',
        bgColor: 'bg-orange-900/20 border-orange-400/30',
        message: 'Your score indicates moderate excessive daytime sleepiness that may be affecting your quality of life.',
        recommendation: 'Medical evaluation recommended to identify potential sleep disorders and underlying causes.',
        action: 'Schedule consultation to discuss sleep patterns and consider further evaluation.'
      };
    } else if (score >= 6) {
      return {
        title: 'Mild Excessive Daytime Sleepiness',
        color: 'text-yellow-400', 
        bgColor: 'bg-yellow-900/20 border-yellow-400/30',
        message: 'Your score suggests mild excessive daytime sleepiness that may benefit from sleep hygiene improvements.',
        recommendation: 'Consider sleep hygiene optimisation and monitor for worsening symptoms.',
        action: 'Implement sleep hygiene strategies and consult healthcare provider if symptoms persist.'
      };
    } else {
      return {
        title: 'Normal Daytime Alertness',
        color: 'text-green-400',
        bgColor: 'bg-green-900/20 border-green-400/30', 
        message: 'Your score indicates normal levels of daytime alertness and low likelihood of problematic sleepiness.',
        recommendation: 'Maintain good sleep hygiene practices to preserve healthy sleep patterns.',
        action: 'Continue current sleep practices and monitor for any changes in sleep quality.'
      };
    }
  };

  const generateAIAnalysis = async () => {
    setLoadingAI(true);
    try {
      const analysis = await getAIAnalysis('Epworth Sleepiness Scale', calculateScore(), answers);
      setAiAnalysis(analysis);
    } catch (error) {
      setAiAnalysis('AI analysis temporarily unavailable. Please consult with a healthcare professional for detailed interpretation.');
    }
    setLoadingAI(false);
  };

  const allAnswered = Object.values(answers).every(answer => answer !== null);
  const score = calculateScore();
  const assessment = getAssessment(score);

  return (
    <div className="bg-slate-800 rounded-xl p-8 border border-slate-700">
      <div className="mb-8">
        <h3 className="text-2xl font-bold text-cream mb-4">Epworth Sleepiness Scale</h3>
        <p className="text-cream opacity-80 mb-6">
          Rate your likelihood of dozing off or falling asleep in the following situations:
        </p>
      </div>

      <div className="space-y-6">
        {questions.map((q, index) => (
          <div key={q.id} className="bg-slate-900 rounded-lg p-6 border border-slate-600">
            <div className="mb-4">
              <h4 className="text-lg font-medium text-cream mb-2">
                {index + 1}. {q.question}
              </h4>
              <p className="text-cream opacity-70 text-sm">{q.scenario}</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {answerOptions.map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleAnswer(q.id, option.value)}
                  className={`px-4 py-3 rounded-lg font-medium transition-all text-sm text-center ${
                    answers[q.id] === option.value
                      ? 'bg-brown text-white shadow-lg'
                      : 'bg-slate-700 text-cream hover:bg-slate-600'
                  }`}
                >
                  <div className="font-semibold">{option.value}</div>
                  <div className="text-xs mt-1">{option.label}</div>
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      {allAnswered && (
        <div className="mt-8">
          <button
            onClick={() => setShowResults(!showResults)}
            className="w-full bg-brown hover:bg-brown/90 text-white font-bold py-4 px-6 rounded-lg transition-colors"
          >
            {showResults ? 'Hide Results' : 'Show My Results'}
          </button>
        </div>
      )}

      {showResults && allAnswered && (
        <div className={`mt-6 p-6 rounded-lg border ${assessment.bgColor}`}>
          <div className="text-center mb-6">
            <h4 className="text-2xl font-bold text-cream mb-2">
              Your Epworth Score: {score}/24
            </h4>
            <div className={`text-xl font-semibold ${assessment.color}`}>
              {assessment.title}
            </div>
          </div>
          
          <div className="space-y-4 text-cream mb-6">
            <p className="text-lg">
              <strong>Assessment:</strong> {assessment.message}
            </p>
            <p className="text-base opacity-80">
              <strong>Recommendation:</strong> {assessment.recommendation}
            </p>
            <p className="text-base opacity-80">
              <strong>Next Steps:</strong> {assessment.action}
            </p>
          </div>

          {/* AI Analysis Section */}
          <div className="bg-slate-900/50 rounded-lg p-4 mb-6">
            <div className="flex items-center justify-between mb-3">
              <h5 className="text-lg font-semibold text-cream">🤖 AI-Powered Analysis</h5>
              {!aiAnalysis && (
                <button
                  onClick={generateAIAnalysis}
                  disabled={loadingAI}
                  className="px-3 py-1 bg-purple/20 text-purple border border-purple/30 rounded hover:bg-purple/30 transition-colors text-sm"
                >
                  {loadingAI ? 'Analyzing...' : 'Get AI Analysis'}
                </button>
              )}
            </div>
            {aiAnalysis && (
              <div className="text-cream opacity-90 text-sm leading-relaxed whitespace-pre-line">
                {aiAnalysis}
              </div>
            )}
          </div>

          {/* Save Results Feature */}
          <div className="bg-slate-800/50 rounded-lg p-4 mb-6">
            <h5 className="text-lg font-semibold text-cream mb-3">Save Your Results</h5>
            <div className="flex flex-wrap gap-3 justify-center">
              <button
                onClick={() => downloadSleepResults('Epworth Sleepiness Scale', score, 24, assessment, answers)}
                className="px-4 py-2 bg-brown/20 text-brown border border-brown/30 rounded-lg hover:bg-brown/30 transition-colors text-sm font-medium"
              >
                📄 Download Report
              </button>
              <button
                onClick={() => shareSleepResults('Epworth Sleepiness Scale', score, 24, assessment)}
                className="px-4 py-2 bg-blue/20 text-blue border border-blue/30 rounded-lg hover:bg-blue/30 transition-colors text-sm font-medium"
              >
                📱 Share Results
              </button>
              <button
                onClick={() => emailSleepResults('Epworth Sleepiness Scale', score, 24, assessment)}
                className="px-4 py-2 bg-green/20 text-green border border-green/30 rounded-lg hover:bg-green/30 transition-colors text-sm font-medium"
              >
                ✉️ Email to GP
              </button>
            </div>
          </div>

          <div className="pt-6 border-t border-slate-600">
            <p className="text-sm text-cream opacity-70 mb-4">
              <strong>Important:</strong> This assessment tool is for screening purposes only and does not replace professional medical evaluation. 
              Consult with a healthcare professional for comprehensive sleep evaluation.
            </p>
            <div className="flex justify-center">
              <a 
                href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-brown text-white px-8 py-3 rounded-lg hover:bg-brown/80 transition-colors font-medium"
              >
                <i className="fas fa-calendar-check mr-2"></i>
                Book Sleep Consultation
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function SleepRecoveryOptimisation() {
  const sleepPillars = [
    {
      icon: "🌙",
      title: "Circadian Rhythm Optimisation",
      description: "Align your body's natural clock for optimal metabolic function",
      features: ["Light exposure protocols", "Meal timing strategies", "Sleep-wake consistency", "Hormone regulation"],
      impact: "Improves insulin sensitivity and leptin production"
    },
    {
      icon: "😴",
      title: "Sleep Hygiene Protocols",
      description: "Create the perfect environment and routine for restorative sleep",
      features: ["Bedroom optimisation", "Pre-sleep routines", "Technology management", "Temperature control"],
      impact: "Enhances sleep quality and duration"
    },
    {
      icon: "🔋",
      title: "Recovery Strategies",
      description: "Support your body's natural recovery and repair processes",
      features: ["Stress reduction techniques", "Active recovery methods", "Inflammation management", "Energy restoration"],
      impact: "Accelerates muscle recovery and fat metabolism"
    },
    {
      icon: "⚖️",
      title: "Hormonal Balance",
      description: "Optimise sleep-related hormones that affect weight management",
      features: ["Cortisol regulation", "Growth hormone optimisation", "Thyroid support", "Insulin sensitivity"],
      impact: "Improves appetite control and metabolic rate"
    }
  ];

  const sleepStages = [
    {
      stage: "Stage 1 - Light Sleep",
      duration: "5-10 minutes",
      function: "Transition from wakefulness",
      weightImpact: "Initial metabolic slowdown",
      color: "bg-blue-200"
    },
    {
      stage: "Stage 2 - True Sleep",
      duration: "45-55% of sleep",
      function: "Memory consolidation begins",
      weightImpact: "Stress hormone reduction",
      color: "bg-blue-400"
    },
    {
      stage: "Stage 3 - Deep Sleep",
      duration: "15-20% of sleep",
      function: "Physical restoration and repair",
      weightImpact: "Growth hormone release, muscle recovery",
      color: "bg-blue-600"
    },
    {
      stage: "REM Sleep",
      duration: "20-25% of sleep",
      function: "Emotional processing and memory",
      weightImpact: "Appetite hormone regulation",
      color: "bg-purple-600"
    }
  ];

  const sleepDisorders = [
    {
      disorder: "Obstructive Sleep Apnoea (OSA)",
      prevalence: "Affects 60-90% of adults with obesity, 24% of men, 9% of women",
      symptoms: ["Loud snoring with witnessed apnoeas", "Excessive daytime sleepiness (Epworth >10)", "Morning headaches", "Concentration difficulties", "Mood changes", "Nocturia"],
      weightConnection: "OSA increases insulin resistance, cortisol levels, and appetite hormones. Weight loss of 10% can reduce AHI by 26%. Creates vicious cycle with weight gain.",
      management: [
        "Comprehensive sleep study assessment",
        "CPAP therapy (gold standard treatment)",
        "Weight loss program (primary intervention)",
        "Sleep positioning therapy",
        "Oral appliance therapy (mild-moderate OSA)",
        "Specialist ENT referral if indicated",
        "RACGP guidelines compliance for ongoing care"
      ],
      resources: "RACGP Sleep Health Toolkit, sleepprimarycareresources.org.au/osa"
    },
    {
      disorder: "Chronic Insomnia",
      prevalence: "10-15% of adults, higher in shift workers and obesity",
      symptoms: ["Sleep onset latency >30 minutes", "Frequent nocturnal awakenings", "Early morning awakening", "Non-restorative sleep", "Daytime impairment", "Sleep-related anxiety"],
      weightConnection: "Chronic insomnia increases ghrelin by 28%, decreases leptin by 18%, and increases cortisol. Associated with 30% increased obesity risk.",
      management: [
        "Sleep hygiene education and assessment",
        "Cognitive Behavioural Therapy for Insomnia (CBT-I)",
        "Sleep restriction therapy",
        "Stimulus control techniques",
        "Relaxation training and mindfulness",
        "Short-term pharmacotherapy if indicated",
        "Address underlying medical conditions"
      ],
      resources: "RACGP Insomnia Management Guidelines"
    },
    {
      disorder: "Shift Work Sleep Disorder (SWSD)",
      prevalence: "10-40% of shift workers, personal clinical experience with 20+ years shift work",
      symptoms: ["Excessive sleepiness during work hours", "Insomnia when attempting sleep", "Reduced cognitive performance", "Gastrointestinal issues", "Mood disturbances", "Social isolation"],
      weightConnection: "Disrupts circadian metabolism, increases cortisol and inflammatory markers. Shift workers have 40% higher obesity risk due to hormonal dysregulation.",
      management: [
        "Strategic light therapy protocols",
        "Melatonin timing optimisation",
        "Nap scheduling strategies",
        "Caffeine timing protocols",
        "Family and social support education",
        "Workplace sleep environment modification",
        "Rotating shift pattern optimisation"
      ],
      resources: "Clinical expertise from 20+ years General Practice and shift work experience"
    },
    {
      disorder: "Restless Legs Syndrome (RLS)",
      prevalence: "5-15% of adults, often underdiagnosed in primary care",
      symptoms: ["Uncomfortable leg sensations", "Irresistible urge to move legs", "Symptoms worse in evening/night", "Temporary relief with movement", "Sleep onset difficulty", "Daytime fatigue"],
      weightConnection: "Prevents deep sleep phases crucial for growth hormone release and muscle recovery. Often associated with iron deficiency affecting metabolism.",
      management: [
        "Iron studies and supplementation if deficient",
        "Folate and B12 assessment",
        "Regular moderate exercise program",
        "Leg massage and stretching",
        "Avoid caffeine and alcohol",
        "Dopaminergic medications if severe",
        "Sleep hygiene optimisation"
      ],
      resources: "Clinical Guidelines for Restless Leg Syndrome"
    },
    {
      disorder: "Sleep-Related Breathing Disorders",
      prevalence: "Often co-occurs with OSA, particularly in metabolic syndrome",
      symptoms: ["Central sleep apnoeas", "Cheyne-Stokes respiration", "Upper airway resistance", "Hypopnoeas", "Oxygen desaturations", "Fragmented sleep"],
      weightConnection: "Creates metabolic stress, increases sympathetic nervous system activity, and disrupts normal appetite regulation hormones.",
      management: [
        "Comprehensive sleep study with CO2 monitoring",
        "Underlying medical condition treatment",
        "CPAP or BiPAP therapy as indicated",
        "Weight management as primary intervention",
        "Cardiac and respiratory assessment",
        "Specialist sleep physician referral",
        "Regular follow-up and monitoring"
      ],
      resources: "Sleep Medicine Society of Australia guidelines"
    },
    {
      disorder: "Circadian Rhythm Disorders",
      prevalence: "Common in modern lifestyle, exacerbated by technology use",
      symptoms: ["Delayed sleep phase", "Advanced sleep phase", "Irregular sleep-wake pattern", "Light sensitivity", "Mood changes", "Cognitive impairment"],
      weightConnection: "Disrupts melatonin and cortisol rhythms, affecting glucose metabolism and appetite regulation. Associated with metabolic syndrome.",
      management: [
        "Light therapy protocols (10,000 lux morning light)",
        "Melatonin therapy timing optimisation",
        "Sleep-wake schedule regulation",
        "Blue light filtering in evening",
        "Regular meal timing",
        "Exercise timing optimisation",
        "Chronotherapy when indicated"
      ],
      resources: "Clinical chronobiology guidelines and circadian health protocols"
    }
  ];

  const practicalTips = [
    {
      category: "Evening Routine",
      icon: "🌅",
      tips: [
        "Dim lights 2 hours before bed",
        "No screens 1 hour before sleep",
        "Light protein snack if hungry",
        "Relaxation practices",
        "Consistent bedtime"
      ]
    },
    {
      category: "Sleep Environment",
      icon: "🛏️", 
      tips: [
        "Room temperature 65-68°F",
        "Blackout curtains or eye mask",
        "White noise or earplugs",
        "Comfortable mattress and pillows",
        "Electronics out of bedroom"
      ]
    },
    {
      category: "Morning Habits",
      icon: "☀️",
      tips: [
        "Consistent wake time",
        "Immediate bright light exposure",
        "Hydrate upon waking",
        "Protein-rich breakfast",
        "Light physical activity"
      ]
    },
    {
      category: "Stress Management",
      icon: "🧘",
      tips: [
        "Daily meditation practice",
        "Progressive muscle relaxation",
        "Journaling or gratitude practice",
        "Deep breathing exercises",
        "Professional support when needed"
      ]
    }
  ];

  return (
    <>
      <Head>
        <title>Sleep & Recovery Optimisation | Sleep for Weight Loss | Downscale Weight Loss Clinic</title>
        <meta name="description" content="Professional sleep optimisation for weight management. Circadian rhythm support, sleep hygiene protocols, and recovery strategies that enhance metabolism and fat loss." />
        <meta name="keywords" content="sleep weight loss Australia, circadian rhythm optimisation, sleep hygiene telehealth, recovery protocols, hormone optimisation, sleep disorders" />
        <link rel="canonical" href="https://www.downscale.health/sleep-recovery-optimisation" />
        
        <meta property="og:title" content="Sleep & Recovery Optimisation | Sleep for Weight Loss" />
        <meta property="og:description" content="Professional sleep optimisation strategies to enhance weight loss through better rest and recovery." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.downscale.health/sleep-recovery-optimisation" />
        
        <script type="application/ld+json">
          {`
            {
              "@context": "https://schema.org",
              "@type": "MedicalWebPage",
              "name": "Sleep & Recovery Optimisation",
              "description": "Sleep optimisation protocols for enhanced weight management and metabolic health",
              "publisher": {
                "@type": "Organization",
                "name": "Downscale Weight Loss Clinic"
              }
            }
          `}
        </script>
      </Head>
      <Header />
      <main className="min-h-screen bg-slate-900">
        {/* Hero Section */}
        <div 
          className="relative min-h-[60vh] flex items-center justify-center overflow-hidden"
          style={{
            backgroundImage: "url(/sleep-hero.jpg)",
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat'
          }}
        >
          <img 
            src="/sleep-hero.jpg" 
            alt="" 
            className="hidden" 
            loading="eager"
          />
          <div className="container mx-auto px-4 relative z-10">
            <div className="max-w-4xl mx-auto text-center">
              <h1
                className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6"
                style={{ color: '#f7f2d3', textShadow: '3px 3px 6px rgba(0,0,0,0.9), 1px 1px 3px rgba(0,0,0,0.8)' }}
              >
                Sleep & Recovery Optimisation
              </h1>
              <div className="w-20 h-1 bg-cream/80 mx-auto mb-6"></div>
              <p 
                className="text-xl md:text-2xl mb-8 max-w-3xl mx-auto"
                style={{ color: '#f7f2d3', textShadow: '2px 2px 4px rgba(0,0,0,0.9), 1px 1px 2px rgba(0,0,0,0.8)' }}
              >
                Professional sleep assessments, CPAP therapy support, and evidence-based strategies for optimising sleep quality and metabolic health
              </p>
              <a 
                href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-brown hover:bg-brown/90 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-colors shadow-xl hover-scale animate-fade-in"
              >
                <i className="fas fa-bed mr-3"></i>
                Optimize Your Sleep
                <i className="fas fa-arrow-right ml-3"></i>
              </a>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-4 py-2">
          <PageNavigation />
        </div>

        {/* Sleep-Weight Connection */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                The Sleep-Weight Connection
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Poor sleep directly impacts weight management through hormonal, metabolic, and behavioral pathways
              </p>
            </div>

            <div className="max-w-6xl mx-auto">
              <div className="grid md:grid-cols-3 gap-8">
                <div className="bg-slate-900 rounded-xl p-8 text-center border border-slate-700">
                  <i className="fas fa-balance-scale text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Hormone Disruption</h3>
                  <p className="text-cream opacity-80 text-sm mb-4">
                    Sleep deprivation increases ghrelin (hunger) and decreases leptin (fullness)
                  </p>
                  <div className="text-brown font-semibold">+30% hunger hormones</div>
                </div>

                <div className="bg-slate-900 rounded-xl p-8 text-center border border-slate-700">
                  <i className="fas fa-fire text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Metabolic Slowdown</h3>
                  <p className="text-cream opacity-80 text-sm mb-4">
                    Poor sleep reduces insulin sensitivity and slows metabolic rate
                  </p>
                  <div className="text-brown font-semibold">-20% metabolism</div>
                </div>

                <div className="bg-slate-900 rounded-xl p-8 text-center border border-slate-700">
                  <i className="fas fa-cookie-bite text-brown text-5xl mb-4"></i>
                  <h3 className="text-xl font-bold text-cream mb-3">Cravings Increase</h3>
                  <p className="text-cream opacity-80 text-sm mb-4">
                    Sleep loss triggers cravings for high-calorie, processed foods
                  </p>
                  <div className="text-brown font-semibold">+25% calorie intake</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Sleep Optimization Pillars */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Comprehensive Sleep Optimisation
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
            </div>

            <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto">
              {sleepPillars.map((pillar, index) => (
                <div
                  key={index}
                  className="bg-slate-800 rounded-xl p-8 hover:bg-slate-750 transition-colors border border-slate-700"
                >
                  <div className="flex items-start mb-6">
                    <div className="text-4xl mr-4">{pillar.icon}</div>
                    <div>
                      <h3 className="text-2xl font-bold text-cream mb-2">{pillar.title}</h3>
                      <p className="text-cream opacity-80 mb-4">{pillar.description}</p>
                      <div className="bg-brown/20 rounded-lg p-3 mb-4">
                        <p className="text-brown font-semibold text-sm">{pillar.impact}</p>
                      </div>
                    </div>
                  </div>
                  
                  <ul className="space-y-3">
                    {pillar.features.map((feature, featureIndex) => (
                      <li
                        key={featureIndex}
                        className="flex items-start text-cream opacity-70"
                      >
                        <i className="fas fa-check text-brown mr-3 mt-1"></i>
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Sleep Stages */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Understanding Sleep Stages & Weight Impact
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Each sleep stage plays a crucial role in metabolic health and weight management
              </p>
            </div>

            <div className="max-w-6xl mx-auto">
              <div className="grid md:grid-cols-2 gap-6">
                {sleepStages.map((stage, index) => (
                  <div
                    key={index}
                    className="bg-slate-900 rounded-xl p-6 border border-slate-700"
                  >
                    <div className="flex items-center mb-4">
                      <div className={`w-4 h-4 rounded-full ${stage.color} mr-3`}></div>
                      <h3 className="text-lg font-bold text-cream">{stage.stage}</h3>
                    </div>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <span className="text-cream opacity-60">Duration:</span>
                        <div className="text-cream">{stage.duration}</div>
                      </div>
                      <div>
                        <span className="text-cream opacity-60">Function:</span>
                        <div className="text-cream">{stage.function}</div>
                      </div>
                      <div className="col-span-2">
                        <span className="text-cream opacity-60">Weight Impact:</span>
                        <div className="text-brown font-semibold">{stage.weightImpact}</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Sleep Disorders */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Comprehensive Sleep Medicine & Weight Management
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <div className="max-w-4xl mx-auto mb-8">
                <div className="bg-brown/10 rounded-xl p-6 border border-brown/30">
                  <div className="flex items-center justify-center mb-4">
                    <i className="fas fa-user-md text-brown text-2xl mr-3"></i>
                    <h3 className="text-xl font-bold text-cream">Clinical Expertise in Sleep Medicine</h3>
                  </div>
                  <p className="text-cream opacity-90 text-lg leading-relaxed mb-4">
                    Drawing from extensive General Practice experience and over 20 years as a shift worker, our approach to sleep disorders 
                    combines evidence-based clinical protocols with real-world understanding of sleep challenges.
                  </p>
                  <div className="grid md:grid-cols-3 gap-4 text-center">
                    <div className="bg-slate-800/50 rounded-lg p-4">
                      <i className="fas fa-moon text-brown text-xl mb-2"></i>
                      <div className="text-cream font-semibold text-sm">OSA Management</div>
                      <div className="text-cream opacity-70 text-xs">CPAP therapy & weight loss protocols</div>
                    </div>
                    <div className="bg-slate-800/50 rounded-lg p-4">
                      <i className="fas fa-clock text-brown text-xl mb-2"></i>
                      <div className="text-cream font-semibold text-sm">Shift Work Experience</div>
                      <div className="text-cream opacity-70 text-xs">Personal & clinical expertise</div>
                    </div>
                    <div className="bg-slate-800/50 rounded-lg p-4">
                      <i className="fas fa-certificate text-brown text-xl mb-2"></i>
                      <div className="text-cream font-semibold text-sm">Evidence-Based Protocols</div>
                      <div className="text-cream opacity-70 text-xs">Clinical best practice guidelines</div>
                    </div>
                  </div>
                </div>
              </div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                From insomnia to obstructive sleep apnoea, comprehensive assessment and treatment tailored to your individual sleep needs
              </p>
            </div>

            <div className="max-w-7xl mx-auto space-y-8">
              {sleepDisorders.map((disorder, index) => (
                <div
                  key={index}
                  className="bg-slate-800 rounded-xl p-8 border border-slate-700 hover:border-brown/50 transition-colors"
                >
                  <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
                    <div className="lg:col-span-1">
                      <h3 className="text-xl font-bold text-cream mb-2">{disorder.disorder}</h3>
                      <p className="text-brown font-semibold text-sm mb-3">{disorder.prevalence}</p>
                      {disorder.resources && (
                        <div className="bg-brown/10 rounded-lg p-3 border border-brown/30">
                          <h5 className="text-brown font-semibold text-xs mb-1">Clinical Resources:</h5>
                          <p className="text-cream opacity-80 text-xs">{disorder.resources}</p>
                        </div>
                      )}
                    </div>
                    <div className="lg:col-span-1">
                      <h4 className="text-lg font-semibold text-cream mb-3 flex items-center">
                        <i className="fas fa-stethoscope text-brown mr-2"></i>
                        Clinical Symptoms
                      </h4>
                      <ul className="space-y-2">
                        {disorder.symptoms.map((symptom, symptomIndex) => (
                          <li key={symptomIndex} className="text-cream opacity-80 text-sm flex items-start">
                            <i className="fas fa-circle text-brown mr-2 mt-2 text-xs"></i>
                            {symptom}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div className="lg:col-span-1">
                      <h4 className="text-lg font-semibold text-cream mb-3 flex items-center">
                        <i className="fas fa-link text-brown mr-2"></i>
                        Weight Connection
                      </h4>
                      <p className="text-cream opacity-80 text-sm leading-relaxed">{disorder.weightConnection}</p>
                    </div>
                    <div className="lg:col-span-1">
                      <h4 className="text-lg font-semibold text-cream mb-3 flex items-center">
                        <i className="fas fa-user-md text-brown mr-2"></i>
                        Evidence-Based Management
                      </h4>
                      <ul className="space-y-2">
                        {disorder.management.map((approach, approachIndex) => (
                          <li key={approachIndex} className="text-cream opacity-80 text-sm flex items-start">
                            <i className="fas fa-check text-brown mr-2 mt-1 text-xs"></i>
                            {approach}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* OSA Clinical Management Section */}
        <section className="py-16 bg-gradient-to-br from-slate-800 to-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Obstructive Sleep Apnoea: Clinical Assessment & Management
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-90 text-lg max-w-3xl mx-auto">
                Evidence-based approach to OSA diagnosis, treatment, and ongoing management from a General Practice perspective
              </p>
            </div>

            <div className="max-w-7xl mx-auto">
              <div className="grid lg:grid-cols-2 gap-8 mb-12">
                {/* Assessment Protocol */}
                <div className="bg-slate-900 rounded-xl p-8 border border-brown/30">
                  <h3 className="text-2xl font-bold text-cream mb-6 flex items-center">
                    <i className="fas fa-clipboard-check text-brown mr-3"></i>
                    Clinical Assessment Protocol
                  </h3>
                  <div className="space-y-4">
                    <div className="bg-slate-800 rounded-lg p-4">
                      <h4 className="text-lg font-semibold text-cream mb-2">Initial Screening</h4>
                      <ul className="space-y-2 text-cream opacity-80 text-sm">
                        <li>• Epworth Sleepiness Scale (greater than 10 indicates excessive daytime sleepiness)</li>
                        <li>• STOP-BANG questionnaire (≥3 high risk for OSA)</li>
                        <li>• Partner-witnessed apnoeas and snoring assessment</li>
                        <li>• BMI calculation and neck circumference measurement</li>
                      </ul>
                    </div>
                    <div className="bg-slate-800 rounded-lg p-4">
                      <h4 className="text-lg font-semibold text-cream mb-2">Sleep Study Indications</h4>
                      <ul className="space-y-2 text-cream opacity-80 text-sm">
                        <li>• High clinical suspicion with STOP-BANG ≥3</li>
                        <li>• Excessive daytime sleepiness with risk factors</li>
                        <li>• Resistant hypertension or atrial fibrillation</li>
                        <li>• Type 2 diabetes with unexplained fatigue</li>
                        <li>• Commercial driver or safety-critical occupation</li>
                      </ul>
                    </div>
                    <div className="bg-brown/10 rounded-lg p-4 border border-brown/30">
                      <h4 className="text-brown font-semibold mb-2 flex items-center">
                        <i className="fas fa-external-link-alt mr-2"></i>
                        Clinical Resources
                      </h4>
                      <p className="text-cream opacity-80 text-sm">
                        Comprehensive OSA resources available at <strong>sleepprimarycareresources.org.au/osa</strong> 
                        providing evidence-based assessment tools and management protocols.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Treatment Pathways */}
                <div className="bg-slate-900 rounded-xl p-8 border border-brown/30">
                  <h3 className="text-2xl font-bold text-cream mb-6 flex items-center">
                    <i className="fas fa-route text-brown mr-3"></i>
                    Treatment Pathways
                  </h3>
                  <div className="space-y-4">
                    <div className="bg-slate-800 rounded-lg p-4">
                      <h4 className="text-lg font-semibold text-cream mb-2">Mild OSA (AHI 5-15)</h4>
                      <ul className="space-y-2 text-cream opacity-80 text-sm">
                        <li>• Weight loss program (primary intervention)</li>
                        <li>• Sleep positioning therapy</li>
                        <li>• Oral appliance therapy consideration</li>
                        <li>• Upper airway exercises</li>
                        <li>• Alcohol and sedative avoidance</li>
                      </ul>
                    </div>
                    <div className="bg-slate-800 rounded-lg p-4">
                      <h4 className="text-lg font-semibold text-cream mb-2">Moderate-Severe OSA (AHI greater than 15)</h4>
                      <ul className="space-y-2 text-cream opacity-80 text-sm">
                        <li>• CPAP therapy (gold standard)</li>
                        <li>• Comprehensive CPAP education and support</li>
                        <li>• Weight management as concurrent therapy</li>
                        <li>• Sleep physician referral for complex cases</li>
                        <li>• Regular follow-up and compliance monitoring</li>
                      </ul>
                    </div>
                    <div className="bg-slate-800 rounded-lg p-4">
                      <h4 className="text-lg font-semibold text-cream mb-2">Specialist Referral Criteria</h4>
                      <ul className="space-y-2 text-cream opacity-80 text-sm">
                        <li>• CPAP intolerance or treatment failure</li>
                        <li>• Complex sleep disorders (central apnoeas)</li>
                        <li>• Surgical candidacy assessment</li>
                        <li>• Occupational driving restrictions</li>
                        <li>• Cardiovascular comorbidities requiring specialist input</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              {/* Weight Loss Impact on OSA */}
              <div className="bg-gradient-to-r from-brown/20 to-slate-800 rounded-xl p-8 border border-brown/50 mb-8">
                <h3 className="text-2xl font-bold text-cream mb-6 text-center">
                  Weight Loss Impact on Sleep Apnoea
                </h3>
                <div className="grid md:grid-cols-3 gap-6">
                  <div className="text-center">
                    <div className="text-4xl font-bold text-brown mb-2">10%</div>
                    <div className="text-cream font-semibold mb-2">Weight Loss</div>
                    <div className="text-cream opacity-80 text-sm">Reduces AHI by 26% on average</div>
                  </div>
                  <div className="text-center">
                    <div className="text-4xl font-bold text-brown mb-2">50%</div>
                    <div className="text-cream font-semibold mb-2">OSA Resolution</div>
                    <div className="text-cream opacity-80 text-sm">With significant weight loss in mild OSA</div>
                  </div>
                  <div className="text-center">
                    <div className="text-4xl font-bold text-brown mb-2">70%</div>
                    <div className="text-cream font-semibold mb-2">CPAP Improvement</div>
                    <div className="text-cream opacity-80 text-sm">Better tolerance with weight reduction</div>
                  </div>
                </div>
              </div>

              {/* Ongoing Management */}
              <div className="bg-slate-900 rounded-xl p-8 border border-slate-700">
                <h3 className="text-2xl font-bold text-cream mb-6 flex items-center">
                  <i className="fas fa-calendar-check text-brown mr-3"></i>
                  Long-term Management & Follow-up
                </h3>
                <div className="grid md:grid-cols-2 gap-8">
                  <div>
                    <h4 className="text-lg font-semibold text-cream mb-4">CPAP Compliance Monitoring</h4>
                    <ul className="space-y-3 text-cream opacity-80 text-sm">
                      <li className="flex items-start">
                        <i className="fas fa-clock text-brown mr-2 mt-1"></i>
                        Monthly compliance reviews for first 3 months
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-chart-line text-brown mr-2 mt-1"></i>
                        Target greater than 4 hours/night, greater than 70% of nights
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-tools text-brown mr-2 mt-1"></i>
                        Equipment maintenance and mask fitting
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-phone text-brown mr-2 mt-1"></i>
                        24/7 technical support access
                      </li>
                    </ul>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold text-cream mb-4">Clinical Follow-up Schedule</h4>
                    <ul className="space-y-3 text-cream opacity-80 text-sm">
                      <li className="flex items-start">
                        <i className="fas fa-calendar text-brown mr-2 mt-1"></i>
                        6-8 weeks post-treatment initiation
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-calendar-alt text-brown mr-2 mt-1"></i>
                        6-monthly reviews for stable patients
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-weight text-brown mr-2 mt-1"></i>
                        Annual weight and OSA severity assessment
                      </li>
                      <li className="flex items-start">
                        <i className="fas fa-heartbeat text-brown mr-2 mt-1"></i>
                        Cardiovascular risk factor monitoring
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* STOP-BANG Assessment Tool */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                STOP-BANG Self-Assessment for OSA
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-80 text-lg max-w-3xl mx-auto">
                A validated screening tool to assess your risk of obstructive sleep apnea. Answer each question honestly for an accurate assessment.
              </p>
            </div>

            <div className="max-w-4xl mx-auto">
              <StopBangAssessment />
            </div>
          </div>
        </section>

        {/* Epworth Sleepiness Scale Assessment */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Epworth Sleepiness Scale Assessment
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-80 text-lg max-w-3xl mx-auto">
                Assess your level of daytime sleepiness using this clinically validated tool. Results help identify excessive sleepiness that may indicate sleep disorders.
              </p>
            </div>

            <div className="max-w-4xl mx-auto">
              <EpworthSleepinessScale />
            </div>
          </div>
        </section>

        {/* Clinical Resources & Downloads */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Clinical Resources & Research
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
              <p className="text-cream opacity-80 text-lg max-w-3xl mx-auto">
                Access evidence-based research and clinical guidelines for sleep disorders and weight management
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto">
              {/* GLP-1 OSA Research */}
              <div className="bg-slate-900 rounded-xl p-8 border border-slate-700 hover:border-brown/50 transition-colors">
                <div className="flex items-start space-x-4">
                  <div className="bg-brown/20 rounded-lg p-3 flex-shrink-0">
                    <i className="fas fa-file-medical text-brown text-2xl"></i>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-cream mb-3">
                      GLP-1 Receptor Agonists for OSA Management
                    </h3>
                    <p className="text-cream opacity-80 text-sm mb-4">
                      Latest research on the efficacy and safety of GLP-1 receptor agonists in managing obstructive sleep apnea in individuals without diabetes. Published in Sleep Medicine 2025.
                    </p>
                    <div className="space-y-2 text-sm text-cream opacity-70 mb-6">
                      <div>• Systematic review and meta-analysis</div>
                      <div>• Evidence from 3 randomized controlled trials</div>
                      <div>• 16.6 events/hour reduction in AHI</div>
                      <div>• Clinical implications for weight management</div>
                    </div>
                    <a 
                      href="/OSAGLP-1_Research_Study.pdf" 
                      download="GLP1_OSA_Research_2025.pdf"
                      className="inline-flex items-center bg-brown text-white px-6 py-3 rounded-lg hover:bg-brown/80 transition-colors"
                    >
                      <i className="fas fa-download mr-2"></i>
                      Download Research Paper
                    </a>
                  </div>
                </div>
              </div>

              {/* Clinical Guidelines */}
              <div className="bg-slate-900 rounded-xl p-8 border border-slate-700 hover:border-brown/50 transition-colors">
                <div className="flex items-start space-x-4">
                  <div className="bg-brown/20 rounded-lg p-3 flex-shrink-0">
                    <i className="fas fa-stethoscope text-brown text-2xl"></i>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-cream mb-3">
                      Sleep Medicine Clinical Guidelines
                    </h3>
                    <p className="text-cream opacity-80 text-sm mb-4">
                      Comprehensive clinical protocols for sleep disorder assessment, diagnosis, and management in primary care settings.
                    </p>
                    <div className="space-y-2 text-sm text-cream opacity-70 mb-6">
                      <div>• OSA screening and diagnosis protocols</div>
                      <div>• CPAP therapy management guidelines</div>
                      <div>• Weight management integration</div>
                      <div>• Follow-up and monitoring standards</div>
                    </div>
                    <a 
                      href="https://www.sleepfoundation.org/how-sleep-works/sleep-apnea-diagnosis" 
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center bg-brown text-white px-6 py-3 rounded-lg hover:bg-brown/80 transition-colors"
                    >
                      <i className="fas fa-external-link-alt mr-2"></i>
                      Access Guidelines
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Practical Sleep Tips */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-cream mb-4">
                Practical Sleep Optimisation Strategies
              </h2>
              <div className="w-16 h-1 bg-brown mx-auto mb-6"></div>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 max-w-7xl mx-auto">
              {practicalTips.map((category, index) => (
                <div
                  key={index}
                  className="bg-slate-900 rounded-xl p-6 hover:bg-slate-750 transition-colors border border-slate-700"
                >
                  <div className="text-center mb-6">
                    <div className="text-4xl mb-3">{category.icon}</div>
                    <h3 className="text-xl font-bold text-cream">{category.category}</h3>
                  </div>
                  
                  <ul className="space-y-3">
                    {category.tips.map((tip, tipIndex) => (
                      <li
                        key={tipIndex}
                        className="flex items-start text-sm text-cream opacity-70"
                      >
                        <i className="fas fa-moon text-brown mr-2 mt-1 text-xs"></i>
                        {tip}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Sleep Tracking */}
        <section className="py-16 bg-slate-900">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto bg-slate-800 rounded-xl p-8 border border-slate-700">
              <div className="text-center mb-8">
                <h2 className="text-3xl font-bold text-cream mb-4">Sleep Tracking & Optimisation</h2>
                <p className="text-cream opacity-80">Monitor your sleep to identify patterns and optimise for weight loss</p>
              </div>
              
              <div className="grid md:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-xl font-bold text-cream mb-4">Track These Metrics:</h3>
                  <ul className="space-y-3">
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-clock text-brown mr-3"></i>
                      Sleep duration (7-9 hours ideal)
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-bed text-brown mr-3"></i>
                      Bedtime consistency
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-chart-line text-brown mr-3"></i>
                      Sleep quality rating
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-exclamation text-brown mr-3"></i>
                      Number of awakenings
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-cream mb-4">Correlate With:</h3>
                  <ul className="space-y-3">
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-utensils text-brown mr-3"></i>
                      Hunger levels next day
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-weight text-brown mr-3"></i>
                      Weight fluctuations
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-battery-three-quarters text-brown mr-3"></i>
                      Energy levels
                    </li>
                    <li className="flex items-center text-cream opacity-80">
                      <i className="fas fa-dumbbell text-brown mr-3"></i>
                      Exercise performance
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 bg-slate-800">
          <div className="container mx-auto px-4">
            <div className="bg-brown/10 rounded-xl p-8 max-w-4xl mx-auto text-center border border-brown/20">
              <h2 className="text-3xl font-bold text-cream mb-4">
                Ready to Optimize Your Sleep for Weight Loss?
              </h2>
              <p className="text-cream opacity-90 text-lg mb-6">
                Get personalised sleep optimisation strategies to enhance your metabolism and support sustainable weight management
              </p>
              <a 
                href="https://www.halaxy.com/book/nurse-practitioner/mr-justin-black/1488401/1198131" 
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-brown hover:bg-brown/90 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-colors"
              >
                <i className="fas fa-moon mr-3"></i>
                Discuss All Pillars - Regular Reviews
              </a>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}