// Routes to prerender at build time - Enhanced for Weight Loss Clinic SEO
export const prerenderRoutes = [
  '/',
  '/about',
  '/pricing', 
  '/blog',
  '/faq',
  '/locations',
  '/how-it-works',
  '/terms',
  '/privacy',
  '/medicare',
  '/complaints',
  '/data-deletion',
  '/medical-weight-management',
  '/nutrition-meal-planning',
  '/movement-activity-programs',
  '/mental-health-support',
  '/sleep-recovery-optimisation',
  '/goal-setting-maintenance',
  // Weight Loss Clinic Location pages - Primary Australian cities
  '/weight-loss-clinic-sydney',
  '/weight-loss-clinic-melbourne',
  '/weight-loss-clinic-brisbane',
  '/weight-loss-clinic-perth',
  '/weight-loss-clinic-adelaide',
  '/weight-loss-clinic-gold-coast',
  '/weight-loss-clinic-canberra',
  '/weight-loss-clinic-newcastle',
  // Additional Australian locations for comprehensive coverage
  '/weight-loss-clinic-hobart',
  '/weight-loss-clinic-darwin',
  '/weight-loss-clinic-geelong',
  '/weight-loss-clinic-sunshine-coast',
  '/weight-loss-clinic-wollongong',
  // Major regional centers
  '/weight-loss-clinic-cairns',
  '/weight-loss-clinic-townsville',
  '/weight-loss-clinic-ballarat',
  '/weight-loss-clinic-bendigo',
  '/weight-loss-clinic-launceston',
  '/weight-loss-clinic-toowoomba',
  '/weight-loss-clinic-mandurah',
  '/weight-loss-clinic-bunbury',
  '/weight-loss-clinic-albury-wodonga',
  '/weight-loss-clinic-wagga-wagga',
  '/weight-loss-clinic-alice-springs',
  '/weight-loss-clinic-mackay',
  '/weight-loss-clinic-rockhampton',
];